name: Echo Script

on: 
  workflow_call:
    inputs:
      envname:
        type: string
        description: 'Default env to run'
        required: true
        default: 'local'
  
jobs:
  deploy-job:
    name: Echo Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Hello, World ${{inputs.envname}}!"
          echo "Branch name is ${{ github.ref }}"
          echo "Head Branch name is ${{ github.head_ref }}"
          echo "Base Branch name is ${{ github.base_ref }}"
