name: Echo Script

on: 
  workflow_call:
    inputs:
      name_var:
        type: string
        description: 'Workflow Variable - Name'
        required: true
        default: ''
      githubenv_var:
        type: string
        description: 'Workflow Variable - Environment'
        required: true
        default: 'beta'

jobs:
  deploy-job:
    name: Echo Deploy Job
    runs-on: ubuntu-latest
    environment: ${{ inputs.githubenv_var }}
    env:
      NAME: ${{ vars.NAME }}
      SECRETNAME: ${{ secrets.NAME }}
    steps:
      - name: echo
        run: |
          echo "EchoScript!"
          echo "-------------------------------------------"
          echo "Workflow Variable name_var - $inputs.name_var"
          echo "Workflow Variable githubenv_var - $inputs.githubenv_var"
          echo "Branch name is ${{ github.ref }}"
          echo "Head Branch name is ${{ github.head_ref }}"
          echo "Base Branch name is ${{ github.base_ref }}"
          echo "EnvVariable name is $NAME"
          echo "SecretVariable Branch name is $SECRETNAME"
