name: Code PR

on:
  pull_request:
    branches:
      - 'main'
jobs:
  
  # login to azure and deploy resources
  azure-login:
    name: Code Pull Request
    runs-on: ubuntu-latest
    environment: sandbox

    # Add env variables for service principal
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      #TF_LOG: DEBUG # Set to DEBUG to see Terraform logs

    steps:
      - name: pull request 
        run: |
          echo "pull request created!"
          echo "Branch name is ${{ github.ref }}"
          echo "Head Branch name is ${{ github.head_ref }}"
          echo "Base Branch name is ${{ github.base_ref }}"