name: Sandbox Terraform Deploy

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'feature/**'    
jobs:
  
  # login to azure and deploy resources
  azure-login:
    name: Resources
    runs-on: ubuntu-latest
    environment: sandbox

    # Add env variables for service principal
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      #TF_LOG: DEBUG # Set to DEBUG to see Terraform logs

    steps:
      - name: pull request 
        run: echo "pull request created!"