name: Code Push

on:
  push:
    branches:
      - '!main'         # code push to any feature branch other than main
      - 'feature/**'
      - 'foo' 
    # paths:
    #   - 'envs/sandbox/**'
  
jobs:

  reusable_workflow:
    name: Reusable Workflow
    uses: ./.github/workflows/echo.yml
    with:
        envname: 'local'

  azure-login:
    name: Feature Branch Push
    runs-on: ubuntu-latest
    environment: sandbox

    # Add env variables for service principal
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      TF_LOG: DEBUG # Set to DEBUG to see Terraform logs

    steps:
      - name: echo 
        run: |
          echo "Push Created!!"
          echo "Branch name is ${{ github.ref }}"
          echo "Head Branch name is ${{ github.head_ref }}"
          echo "Base Branch name is ${{ github.base_ref }}"