name: Sandbox Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'sandbox/**'
  
# permissions on workflow uses id-token: write. 
# You won't be able to request the OIDC JWT ID token if the permissions setting for id-token is set to read or none.
permissions:
  id-token: write
  contents: read      
  pull-requests: write

jobs:
  
  # login to azure and deploy resources
  azure-login:
    name: Resources
    runs-on: ubuntu-latest
    environment: sandbox

    # Add env variables for service principal
    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      #TF_LOG: DEBUG # Set to DEBUG to see Terraform logs

    steps:
      - name: echo 
        run: echo "code added!"